name: Automated deploy

on:
  release:
    types: [created]

env:
  TARGET_REF: ${{ github.event.release.target_commitish }}
  TAG: ${{ github.event.release.target_commitish == 'master' && 'latest' || 'next' }}

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/npm

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Build package
        run: npm run build:all

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            dist
            package.json
            package-lock.json
            README.md
            LICENSE

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
          token: ${{ secrets.GPR_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Install deps
        uses: ./.github/workflows/composite/npm

      - name: Publish package to NPM
        run: npm run publish:all -- --tag $TAG
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
